import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    fr: {
        welcome: "Bienvenue sur Mysterious Classroom",
        dashboard_title: "Tableau de bord",
        account_title: "Mon Compte",
        courses: "Mes Cours",
        admin: "Admin",
        monitor: "Moniteur",
        logout: "Déconnexion",
        projects: "Projets",
        leaderboard: "Classement",
        nav: {
            login: "SE CONNECTER",
            register: "S'INSCRIRE"
        },
        onboarding: {
            title: "Personnalise ton espace",
            theme: "Thème",
            dark: "Sombre",
            light: "Clair",
            language: "Langue du contenu",
            active: "Activé",
            mute: "Muet",
            next: "Suivant",
            back: "Retour",
            start: "Commencer"
        },
        onboardingFlow: {
            forced_beginner: "On t'a mis en Débutant pour commencer sereinement !",
            welcome_interface: "Bienvenue sur l'interface !",
            save_error: "Erreur lors de la sauvegarde.",
            network_error: "Erreur réseau",
            title: "Finalisation",
            subtitle: "Configurez votre accès local",
            google_pwd_info: "Bienvenue ! Comme tu es connecté via Google, définis un mot de passe pour pouvoir te connecter directement avec <strong class=\"text-blue-600\">{email}</strong> la prochaine fois.",
            pwd_placeholder: "Mot de passe",
            confirm_pwd_placeholder: "Confirmer le mot de passe",
            pwd_mismatch: "Les mots de passe ne correspondent pas",
            invalid_pwd: "Veuillez remplir un mot de passe valide.",
            continue: "Continuer",
            goal_question: "Quel est ton objectif principal ?",
            goal_1: "Découvrir le code",
            goal_2: "Créer des sites web",
            goal_3: "Devenir développeur",
            goal_4: "Passer des examens",
            back: "Retour",
            next: "Suivant",
            level_question: "Quel est ton niveau actuel ?",
            level_beginner_title: "Total Débutant",
            level_beginner_desc: "Je n'ai jamais codé de ma vie",
            level_inter_title: "Intermédiaire",
            level_inter_desc: "J'ai déjà quelques bases solides",
            level_adv_title: "Avancé",
            level_adv_desc: "Je code déjà en autonomie complète",
            creating: "Création...",
            validate_create: "Valider & Créer 🎉"
        },
        projectsList: {
            auth_error: "Non authentifié",
            load_error: "Erreur lors du chargement des données",
            load_failed: "Impossible de charger les projets :",
            submit_error: "Erreur lors de la soumission",
            project_validated: "Projet validé ! +{xp} XP",
            lab_title: "LABORATOIRE DE PROJETS",
            hero_title1: "Quêtes",
            hero_title2: "& Projets de Code",
            hero_desc: "Débloquez vos compétences d'ingénieur. Je prépare de nouveaux défis pratiques et interactifs.",
            available: "Projets Disponibles",
            completed: "Projets Accomplis",
            quests_title: "Défis & Quêtes",
            wip_title: "Nouveaux Projets en Préparation",
            wip_desc: "✨ Le site est actuellement en cours d'amélioration. La plateforme Mysterious Classroom prépare son tout nouvel écosystème de projets et défis pratiques !",
            language: "Langage:",
            unlock_req: "Validez \"{lang} - Avancé\" pour débloquer.",
            context: "Contexte",
            target_level: "Niveau Cible",
            xp_reward: "Récompense XP",
            requirements: "Cahier des charges",
            objectives: "Objectifs pédagogiques",
            already_validated: "Projet déjà validé",
            validate_btn: "Valider ce projet",
            certify_msg: "En validant, vous certifiez avoir réalisé ce projet en autonomie en respectant le cahier des charges expresse."
        },
        leaderboard: {
            auth_error: "Non authentifié",
            load_error: "Erreur lors du chargement du classement",
            load_failed: "Impossible de charger le classement :",
            title1: "Temple de la",
            title2: "Renommée",
            desc: "Découvre les meilleurs aventuriers de Mysterious Classroom. Gagne de l'XP en complétant des cours pour grimper dans le classement !",
            adventurer: "Aventurier",
            lvl: "Niv",
            empty: "Aucun apprenti n'est encore classé. Gagne de l'XP pour devenir le premier !"
        },
        privacy: {
            title: "Politique de Confidentialité",
            priority: "Votre confiance est notre priorité absolue.",
            intro: "Chez <strong>Mysterious Classroom</strong>, nous croyons en une transparence totale et une sécurité sans faille.",
            h1: "1. Collecte de Données",
            p1: "Nous collectons uniquement les informations nécessaires à votre progression : votre nom, email et votre avancement dans les cours.",
            h2: "2. Usage des Données",
            p2: "Vos données servent exclusivement à personnaliser votre expérience d'apprentissage. Nous ne partageons jamais vos informations avec des tiers.",
            h3: "3. Sécurité",
            p3: "Toutes vos données sont chiffrées et stockées sur des serveurs sécurisés.",
            last_update: "Dernière mise à jour : 18 Février 2026"
        },
        terms: {
            title: "Conditions d'Utilisation",
            h1: "1. Acceptation des Conditions",
            p1: "En accédant à Mysterious Classroom, vous acceptez d'être lié par les présentes conditions d'utilisation.",
            h2: "2. Compte Utilisateur",
            p2: "Vous êtes responsable de maintenir la confidentialité de votre compte.",
            h3: "3. Contenu des Cours",
            p3: "Le contenu des cours est protégé par les droits d'auteur.",
            last_update: "Dernière mise à jour : 18 Février 2026"
        },
        dashboard: {
            subtitle: "Votre aventure commence ici",
            modules: "Modules",
            badges: "Badges",
            points: "Points",
            completed_projects: "Projets Terminés",
            latest_badges: "Derniers Badges",
            no_badges: "Vous n'avez pas encore de badges.",
            recommended: "Recommandé pour vous",
            continue: "Continuer",
            start: "Commencer",
            completed: "Terminé",
            module_label: "Module :",
            view_all: "Voir tout",
            unlocked: "Débloqué !",
            unlocked_badge: "Félicitations, vous venez de débloquer le badge :",
            tour_completed: "Félicitations pour avoir complété ton initiation. L'aventure commence vraiment maintenant.",
            category_resume: "Reprendre l'apprentissage",
            category_favorites: "Mes Cours Favoris",
            access_authorized: "Accès Autorisé",
            skills_validated: "Tes compétences ont été validées. Tu as débloqué :",
            start_now: "Démarrer maintenant",
            learning_system: "Système d'Apprentissage",
            welcome_user: "BIENVENUE,",
            quote: "La maîtrise n'est pas une destination, mais une quête perpétuelle.",
            ready: "Prêt à continuer ton ascension vers l'élite ?",
            new_modules_title: "Nouveaux Modules en Préparation",
            new_modules_desc: "La plateforme Mysterious Classroom prépare son nouvel écosystème de cours interactifs. L'infrastructure est prête et les futurs modules arriveront très bientôt !",
            unlock_premium: "Débloquer",
            level: "Niveau",
            locked: "Verrouillé",
            take_test: "Passer le test",
            progress: "Progression",
            start_course: "Commencer"
        },
        home: {
            title_part1: "MYSTERIOUS",
            title_part2: "CLASSROOM",
            hero_desc: "L'arène d'entraînement ultime pour <strong class=\"text-slate-900\">apprendre la cybersécurité</strong>, maîtriser l'investigation numérique et résoudre des scénarios CTF concrets.",
            objective_title: "Objectif de la plateforme MYSTERIOUS CLASSROOM",
            objective_desc: "<strong>MYSTERIOUS CLASSROOM</strong> est une plateforme de simulation immersive (CTF). Ma vocation est de vous plonger dans des environnements virtuels où chaque mission consiste à auditer du code, exploiter des vulnérabilités, sécuriser des serveurs et capturer des \"Flags\" pour forger votre expertise cyber.",
            btn_create_agent: "CRÉER UN DOSSIER D'AGENT",
            stats_registered: "Agents Inscrits",
            stats_active: "Opérationnels",
            operations_arsenal: "OPÉRATIONS & ARSENAL",
            explore_vectors: "Explorez les Vecteurs d'Attaque",
            vectors_desc: "Chaque discipline est une arme essentielle pour comprendre, attaquer et défendre les systèmes informatiques critiques.",
            mission_prep: "Mission en préparation",
            architect_tag: "L'ARCHITECTE SYSTÈME",
            architect_quote: "Je crois en un monde où la technologie doit être comprise pour être sécurisée. Mysterious Classroom est l'arène que j'ai bâtie pour forger la prochaine génération d'experts cyber.",
            intercept_tag: "TRANSMISSION INTERCEPTÉE",
            intercept_title: "Le Système est en cours de déploiement",
            intercept_desc: "J'injecte actuellement les nouveaux scénarios d'entraînement (CTF) dans la matrice. La plateforme évolue. Préparez-vous pour de nouvelles missions imminentes.",
            intercept_status: "Compilation des missions en cours...",
            topic_sys_name: "Shell & Linux",
            topic_sys_tag: "Système",
            topic_sys_desc: "Maîtrisez les environnements UNIX, analysez les logs systèmes et manipulez le shell Bash en profondeur.",
            topic_web_name: "Exploitation Web",
            topic_web_tag: "Réseau & Web",
            topic_web_desc: "Simulez des attaques (XSS, SQLi, LFI) sur nos serveurs isolés et apprenez à colmater les brèches.",
            topic_crypto_name: "Cryptographie",
            topic_crypto_tag: "Logique & Maths",
            topic_crypto_desc: "Déchiffrez des messages encodés, étudiez la cryptographie moderne et la théorie des nombres.",
            topic_rev_name: "Reverse Engineering",
            topic_rev_tag: "Analyse Binaire",
            topic_rev_desc: "Désassemblez des exécutables, analysez la mémoire et découvrez comment les programmes fonctionnent sous le capot."
        },
        accountPage: {
            back_to_dashboard: "Retour au tableau de bord"
        },
        account: {
            save: "Sauvegarder",
            member_since: "Membre depuis",
            student: "Étudiant",
            email: "Email",
            preferences: "Préférences d'apprentissage",
            delete_account: "Supprimer mon compte"
        },
        course: {
            level_locked_warning: "Vous devez terminer le niveau précédent pour accéder à ce cours.",
            loading_error: "Erreur de chargement",
            loading_course: "Chargement du cours...",
            not_found_title: "Cours introuvable",
            not_found_message: "Oups ! Ce cours n'existe pas ou a été retiré.",
            session_expired: "Session expirée. Reconnecte-toi.",
            lesson_validated: "Leçon validée ! Bravo 🚀",
            validation_error: "Erreur lors de la validation",
            network_error: "Erreur réseau",
            back_to_courses: "Retour aux cours",
            students: "étudiants",
            motivation: "Motivation",
            start_course_map: "DÉMARRER LA CARTE DU COURS"
        },
        chapter: {
            loading: "Chargement...",
            in_construction: "Chapitre en construction",
            not_interactive: "Désolé ! Ce chapitre n'est pas encore interactif. Nos équipes travaillent pour le rendre disponible très bientôt.",
            save_error: "Impossible de sauvegarder la progression",
            skip_step: "Passer l'étape",
            step: "Étape",
            completed_title: "Chapitre Terminé !",
            completed_desc: "Quel talent ! Tu as débloqué de nouvelles connaissances indispensables. Prêt(e) pour le prochain défi ?",
            back_to_course: "Retour au plan du cours"
        },
        profile_fields: {
            first_name: "Prénom",
            last_name: "Nom",
            email: "Email",
            verified: "Vérifié",
            phone: "Téléphone",
            location: "Localisation",
            privacy: "Confidentialité du profil",
            privacy_public: "Public (visible au classement)",
            privacy_private: "Privé",
            privacy_anonymous: "Anonyme",
            level: "Niveau de programmation",
            level_beginner: "Débutant",
            level_intermediate: "Intermédiaire",
            level_advanced: "Avancé",
            password: "Mot de passe",
            change_password: "Changer le mot de passe",
            current_password: "Mot de passe actuel",
            new_password: "Nouveau mot de passe",
            confirm_password: "Confirmer le nouveau",
            updating: "Mise à jour en cours...",
            update_password: "Mettre à jour le mot de passe",
            two_factor: "Authentification à deux facteurs",
            two_factor_enabled: "Activée",
            two_factor_ready: "Service 2FA prêt",
            active_sessions: "Sessions actives",
            session_active: "session(s) active(s) (Cet appareil)",
            preferences: "Préférences du Compte",
            notifications: "Notifications par email",
            notifications_desc: "Recevoir des emails de notification importants.",
            language: "Langue de l'interface",
            language_desc: "Choisir la langue d'affichage globale du site (Français / English).",
            theme: "Thème Dynamique",
            theme_desc: "Gérer l'apparence visuelle pour plus de confort.",
            theme_light: "Clair",
            theme_dark: "Sombre",
            delete_warning1: "Action irréversible",
            delete_warning1_desc: "Êtes-vous absolument sûr de vouloir supprimer votre compte ?",
            delete_warning2: "Dernière chance",
            delete_warning2_desc: "Toutes vos progressions, favoris et données personnelles seront supprimés pour toujours.",
            yes_understand: "Oui, je comprends",
            confirm_delete: "Confirmer la suppression",
            cancel: "Annuler",
            profile_tab: "Profil",
            security_tab: "Sécurité",
            preferences_tab: "Préférences",
            export_data: "Exporter mes données",
            exporting: "Export en cours...",
            logout_all: "Déconnexion de tous les appareils"
        },
        footer: {
            innovative_platform: "Plateforme d'apprentissage innovante créée avec passion pour l'éducation technologique et le partage des connaissances.",
            creator: "Créateur",
            technologies: "Technologies",
            made_with_passion: "Fait avec passion et l'aide de l'IA",
            platform_created_by: "Plateforme créée par"
        },
        authPage: {
            verification: "Vérification",
            signin: "Connexion",
            signup: "Inscription",
            two_factor_prompt: "Saisis le code 2FA envoyé à ton téléphone",
            code_sent_to: "Code envoyé à",
            verify: "Vérifier",
            activate_account: "Activer mon compte",
            resend_code: "Renvoyer le code",
            firstname: "Prénom",
            lastname: "Nom",
            email: "Email",
            password: "Mot de passe",
            confirm_password: "Confirmer le mot de passe",
            accept_policy: "J'accepte la ",
            policy: "politique de confidentialité",
            accept_terms: "J'accepte les ",
            terms: "conditions d'utilisation",
            passwords_mismatch: "Les mots de passe ne correspondent pas",
            forgot_password: "Mot de passe oublié ?",
            direct_login: "Se connecter directement avec cet email",
            google_login: "Se connecter avec Google",
            set_local_password: "🔑 Définir un mot de passe local pour ce compte",
            loading: "Chargement...",
            creating: "Création...",
            or_with: "ou avec",
            no_account: "Pas de compte ?",
            already_account: "Déjà un compte ?",
            email_required_reset: "Veuillez saisir votre adresse email pour réinitialiser le mot de passe.",
            reset_email_sent: "Email de réinitialisation envoyé ! Consultez votre boîte mail.",
            policy_title: "Politique de Confidentialité",
            terms_title: "Conditions d'Utilisation",
            collection_title: "🛡️ 1. Collecte des données",
            collection_desc: "Sur Mysterious Classroom, nous recueillons uniquement les informations essentielles pour créer votre espace d'apprentissage : prénom, nom, adresse email et votre niveau initial.",
            usage_title: "🎯 2. Utilisation des données",
            usage_desc: "Vos données sont utilisées exclusivement pour :",
            usage_list1: "Sauvegarder votre progression dans les cours et exercices.",
            usage_list2: "Calculer votre score XP, vos streaks et vos badges de réussite.",
            usage_list3: "Adapter les recommandations et l'assistance de notre IA pédagogique.",
            security_title: "🔒 3. Sécurité & Confidentialité",
            security_desc: "Vos mots de passe sont chiffrés avec bcrypt. Nous ne revendons ni ne partageons jamais vos données personnelles à des tiers.",
            rights_title: "⚙️ 4. Vos Droits",
            rights_desc: "Vous disposez d'un droit d'accès, d'exportation et de suppression définitive de votre compte à tout moment depuis les paramètres de votre profil."
        },
        footer_extended: {
            creator: "Créateur",
            technologies: "Technologies",
            innovative_platform: "Plateforme d'apprentissage innovante créée avec passion pour l'éducation technologique et le partage des connaissances.",
            rights: "Mysterious Classroom. Plateforme créée par",
            creator_title: "Étudiant en 1ère année — ESP Dakar",
            bio_1: "Je crois en un monde où la technologie est accessible à tous.",
            bio_2: "Mysterious Classroom est ma contribution pour rendre l'apprentissage du code gratuit, fun et interactif.",
            bio_3: "Étudiant passionné par la transmission du savoir."
        },
        copilot: {
            welcome: "Bonjour",
            ready: "Prêt à apprendre la logique des algorithmes ?"
        }
    },
    en: {
        welcome: "Welcome to Mysterious Classroom",
        dashboard_title: "Dashboard",
        account_title: "Account",
        courses: "My Courses",
        admin: "Admin",
        monitor: "Monitor",
        logout: "Logout",
        projects: "Projects",
        leaderboard: "Leaderboard",
        nav: {
            login: "LOG IN",
            register: "SIGN UP"
        },
        onboarding: {
            title: "Personalize your space",
            theme: "Theme",
            dark: "Dark",
            light: "Light",
            language: "Content Language",
            active: "Enabled",
            mute: "Muted",
            next: "Next",
            back: "Back",
            start: "Start"
        },
        onboardingFlow: {
            forced_beginner: "We set you to Beginner so you can start smoothly!",
            welcome_interface: "Welcome to the interface!",
            save_error: "Error while saving.",
            network_error: "Network error",
            title: "Finalization",
            subtitle: "Configure your local access",
            google_pwd_info: "Welcome! Since you logged in via Google, set a password so you can log in directly with <strong class=\"text-blue-600\">{email}</strong> next time.",
            pwd_placeholder: "Password",
            confirm_pwd_placeholder: "Confirm password",
            pwd_mismatch: "Passwords do not match",
            invalid_pwd: "Please enter a valid password.",
            continue: "Continue",
            goal_question: "What is your main goal?",
            goal_1: "Discover coding",
            goal_2: "Create websites",
            goal_3: "Become a developer",
            goal_4: "Pass exams",
            back: "Back",
            next: "Next",
            level_question: "What is your current level?",
            level_beginner_title: "Total Beginner",
            level_beginner_desc: "I have never coded in my life",
            level_inter_title: "Intermediate",
            level_inter_desc: "I already have some solid basics",
            level_adv_title: "Advanced",
            level_adv_desc: "I can already code in complete autonomy",
            creating: "Creating...",
            validate_create: "Validate & Create 🎉"
        },
        projectsList: {
            auth_error: "Not authenticated",
            load_error: "Error loading data",
            load_failed: "Unable to load projects:",
            submit_error: "Error submitting",
            project_validated: "Project validated! +{xp} XP",
            lab_title: "PROJECTS LABORATORY",
            hero_title1: "Quests",
            hero_title2: "& Code Projects",
            hero_desc: "Unlock your engineering skills. Our teams are preparing new practical and interactive challenges.",
            available: "Available Projects",
            completed: "Completed Projects",
            quests_title: "Challenges & Quests",
            wip_title: "New Projects in Preparation",
            wip_desc: "✨ The site is currently being improved. The Mysterious Classroom platform is preparing its brand new ecosystem of projects and practical challenges!",
            language: "Language:",
            unlock_req: "Validate \"{lang} - Advanced\" to unlock.",
            context: "Context",
            target_level: "Target Level",
            xp_reward: "XP Reward",
            requirements: "Specifications",
            objectives: "Educational Objectives",
            already_validated: "Project already validated",
            validate_btn: "Validate this project",
            certify_msg: "By validating, you certify having completed this project independently in compliance with the express specifications."
        },
        leaderboard: {
            auth_error: "Not authenticated",
            load_error: "Error loading leaderboard",
            load_failed: "Unable to load leaderboard:",
            title1: "Hall of",
            title2: "Fame",
            desc: "Discover the best adventurers of Mysterious Classroom. Earn XP by completing courses to climb the leaderboard!",
            adventurer: "Adventurer",
            lvl: "Lvl",
            empty: "No apprentice is ranked yet. Earn XP to become the first!"
        },
        privacy: {
            title: "Privacy Policy",
            priority: "Your trust is our top priority.",
            intro: "At <strong>Mysterious Classroom</strong>, we believe in total transparency and flawless security.",
            h1: "1. Data Collection",
            p1: "We only collect information necessary for your progression: your name, email, and your course advancement.",
            h2: "2. Data Usage",
            p2: "Your data is used exclusively to personalize your learning experience. We never share your information with third parties.",
            h3: "3. Security",
            p3: "All your data is encrypted and stored on secure servers.",
            last_update: "Last updated: February 18, 2026"
        },
        terms: {
            title: "Terms of Service",
            h1: "1. Acceptance of Terms",
            p1: "By accessing Mysterious Classroom, you agree to be bound by these terms of service.",
            h2: "2. User Account",
            p2: "You are responsible for maintaining the confidentiality of your account.",
            h3: "3. Course Content",
            p3: "Course content is protected by copyright.",
            last_update: "Last updated: February 18, 2026"
        },
        dashboard: {
            subtitle: "Your adventure begins here",
            modules: "Modules",
            badges: "Badges",
            points: "Points",
            completed_projects: "Completed Projects",
            latest_badges: "Latest Badges",
            no_badges: "You don't have any badges yet.",
            recommended: "Recommended for you",
            continue: "Continue",
            start: "Start",
            completed: "Completed",
            module_label: "Module:",
            view_all: "View all",
            unlocked: "Unlocked!",
            unlocked_badge: "Congratulations, you just unlocked the badge:",
            tour_completed: "Congratulations on completing your initiation. The adventure truly begins now.",
            category_resume: "Resume Learning",
            category_favorites: "My Favorite Courses",
            access_authorized: "Access Authorized",
            skills_validated: "Your skills have been validated. You unlocked:",
            start_now: "Start now",
            learning_system: "Learning System",
            welcome_user: "WELCOME,",
            quote: "Mastery is not a destination, but a perpetual quest.",
            ready: "Ready to continue your ascent to the elite?",
            new_modules_title: "New Modules in Preparation",
            new_modules_desc: "The Mysterious Classroom platform is preparing its new ecosystem of interactive courses. The infrastructure is ready and future modules will arrive very soon!",
            unlock_premium: "Unlock",
            level: "Level",
            locked: "Locked",
            take_test: "Take the test",
            progress: "Progress",
            start_course: "Start"
        },
        home: {
            title_part1: "MYSTERIOUS",
            title_part2: "CLASSROOM",
            hero_desc: "The ultimate training arena to learn cybersecurity, master digital forensics, and solve real-world CTF scenarios.",
            objective_title: "Objective of the MYSTERIOUS CLASSROOM platform",
            objective_desc: "MYSTERIOUS CLASSROOM is an immersive simulation platform (CTF). Our mission is to immerse you in virtual environments where each task consists of auditing code, exploiting vulnerabilities, securing servers, and capturing \"Flags\" to forge your cyber expertise.",
            btn_create_agent: "CREATE AN AGENT DOSSIER",
            stats_registered: "Registered Agents",
            stats_active: "Operational",
            operations_arsenal: "OPERATIONS & ARSENAL",
            explore_vectors: "Explore Attack Vectors",
            vectors_desc: "Each discipline is an essential weapon to understand, attack, and defend critical computer systems.",
            mission_prep: "Mission in preparation",
            architect_tag: "THE SYSTEM ARCHITECT",
            architect_quote: "I believe in a world where technology must be understood to be secured. Mysterious Classroom is the arena I built to forge the next generation of cyber experts.",
            intercept_tag: "TRANSMISSION INTERCEPTED",
            intercept_title: "The System is currently deploying",
            intercept_desc: "I am currently injecting new training scenarios (CTF) into the matrix. The platform is evolving. Prepare for upcoming missions.",
            intercept_status: "Compiling missions in progress...",
            topic_sys_name: "Shell & Linux",
            topic_sys_tag: "System",
            topic_sys_desc: "Master UNIX environments, analyze system logs, and deeply manipulate the Bash shell.",
            topic_web_name: "Web Exploitation",
            topic_web_tag: "Network & Web",
            topic_web_desc: "Simulate attacks (XSS, SQLi, LFI) on our isolated servers and learn to patch breaches.",
            topic_crypto_name: "Cryptography",
            topic_crypto_tag: "Logic & Math",
            topic_crypto_desc: "Decrypt encoded messages, study modern cryptography and number theory.",
            topic_rev_name: "Reverse Engineering",
            topic_rev_tag: "Binary Analysis",
            topic_rev_desc: "Disassemble executables, analyze memory, and discover how programs work under the hood."
        },
        accountPage: {
            back_to_dashboard: "Back to dashboard"
        },
        account: {
            save: "Save",
            member_since: "Member since",
            student: "Student",
            email: "Email",
            preferences: "Learning Preferences",
            delete_account: "Delete my account"
        },
        course: {
            level_locked_warning: "You must complete the previous level to access this course.",
            loading_error: "Loading error",
            loading_course: "Loading course...",
            not_found_title: "Course not found",
            not_found_message: "Oops! This course does not exist or has been removed.",
            session_expired: "Session expired. Please log in again.",
            lesson_validated: "Lesson validated! Well done 🚀",
            validation_error: "Validation error",
            network_error: "Network error",
            back_to_courses: "Back to courses",
            students: "students",
            motivation: "Motivation",
            start_course_map: "START COURSE MAP"
        },
        chapter: {
            loading: "Loading...",
            in_construction: "Chapter under construction",
            not_interactive: "Sorry! This chapter is not yet interactive. Our teams are working to make it available very soon.",
            save_error: "Unable to save progress",
            skip_step: "Skip step",
            step: "Step",
            completed_title: "Chapter Completed!",
            completed_desc: "What talent! You have unlocked essential new knowledge. Ready for the next challenge?",
            back_to_course: "Back to course plan"
        },
        profile_fields: {
            first_name: "First Name",
            last_name: "Last Name",
            email: "Email",
            verified: "Verified",
            phone: "Phone",
            location: "Location",
            privacy: "Profile Privacy",
            privacy_public: "Public (visible on leaderboard)",
            privacy_private: "Private",
            privacy_anonymous: "Anonymous",
            level: "Programming Level",
            level_beginner: "Beginner",
            level_intermediate: "Intermediate",
            level_advanced: "Advanced",
            password: "Password",
            change_password: "Change Password",
            current_password: "Current password",
            new_password: "New password",
            confirm_password: "Confirm new password",
            updating: "Updating...",
            update_password: "Update password",
            two_factor: "Two-Factor Authentication",
            two_factor_enabled: "Enabled",
            two_factor_ready: "2FA Service ready",
            active_sessions: "Active Sessions",
            session_active: "active session(s) (This device)",
            preferences: "Account Preferences",
            notifications: "Email Notifications",
            notifications_desc: "Receive important notification emails.",
            language: "Interface language",
            language_desc: "Choose the global display language for the site (French / English).",
            theme: "Dynamic Theme",
            theme_desc: "Manage the visual appearance for more comfort.",
            theme_light: "Light",
            theme_dark: "Dark",
            delete_account: "Delete my account",
            delete_warning1: "Irreversible action",
            delete_warning1_desc: "Are you absolutely sure you want to delete your account?",
            delete_warning2: "Last chance",
            delete_warning2_desc: "All your progress, favorites, and personal data will be deleted forever.",
            yes_understand: "Yes, I understand",
            confirm_delete: "Confirm deletion",
            cancel: "Cancel",
            profile_tab: "Profile",
            security_tab: "Security",
            preferences_tab: "Preferences",
            export_data: "Export my data",
            exporting: "Exporting...",
            logout_all: "Logout from all devices"
        },
        footer: {
            innovative_platform: "Innovative learning platform created with passion for tech education and knowledge sharing.",
            creator: "Creator",
            technologies: "Technologies",
            made_with_passion: "Made with passion and AI assistance",
            platform_created_by: "Platform created by"
        },
        authPage: {
            verification: "Verification",
            signin: "Sign In",
            signup: "Sign Up",
            two_factor_prompt: "Enter the 2FA code sent to your phone",
            code_sent_to: "Code sent to",
            verify: "Verify",
            activate_account: "Activate my account",
            resend_code: "Resend code",
            firstname: "First Name",
            lastname: "Last Name",
            email: "Email",
            password: "Password",
            confirm_password: "Confirm Password",
            accept_policy: "I accept the ",
            policy: "privacy policy",
            accept_terms: "I accept the ",
            terms: "terms of service",
            passwords_mismatch: "Passwords do not match",
            forgot_password: "Forgot password?",
            direct_login: "Login directly with this email",
            google_login: "Sign in with Google",
            set_local_password: "🔑 Set a local password for this account",
            loading: "Loading...",
            creating: "Creating...",
            or_with: "or with",
            no_account: "No account?",
            already_account: "Already have an account?",
            email_required_reset: "Please enter your email address to reset the password.",
            reset_email_sent: "Reset email sent! Check your inbox.",
            policy_title: "Privacy Policy",
            terms_title: "Terms of Service",
            collection_title: "🛡️ 1. Data Collection",
            collection_desc: "On Mysterious Classroom, we only collect essential information to create your learning space: first name, last name, email address, and your initial level.",
            usage_title: "🎯 2. Data Usage",
            usage_desc: "Your data is exclusively used to:",
            usage_list1: "Save your progress in courses and exercises.",
            usage_list2: "Calculate your XP score, streaks, and achievement badges.",
            usage_list3: "Adapt recommendations and assistance from our pedagogical AI.",
            security_title: "🔒 3. Security & Privacy",
            security_desc: "Your passwords are encrypted with bcrypt. We never sell or share your personal data with third parties.",
            rights_title: "⚙️ 4. Your Rights",
            rights_desc: "You have the right to access, export, and permanently delete your account at any time from your profile settings."
        },
        footer_extended: {
            creator: "Creator",
            technologies: "Technologies",
            innovative_platform: "Innovative learning platform created with passion for tech education and knowledge sharing.",
            rights: "Mysterious Classroom. Platform created by",
            creator_title: "1st Year Student — ESP Dakar",
            bio_1: "I believe in a world where technology is accessible to everyone.",
            bio_2: "Mysterious Classroom is my contribution to making coding education free, fun, and interactive.",
            bio_3: "Student passionate about knowledge sharing."
        },
        copilot: {
            welcome: "Hello",
            ready: "Ready to learn the logic of algorithms?",
            ask_placeholder: "Ask me a question about the code...",
            thinking: "I am thinking...",
            no_token: "No authentication token found. Please log in.",
            error: "An error occurred.",
            try_again: "Try again"
        }
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const saved = localStorage.getItem('language');
        if (saved) return saved;
        if (typeof navigator !== 'undefined') {
            const browserLang = navigator.language || navigator.userLanguage;
            if (browserLang && browserLang.toLowerCase().startsWith('en')) {
                return 'en';
            }
        }
        return 'fr';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => {
        const keys = key.split('.');
        let result = translations[language];
        for (const k of keys) {
            if (result && result[k] !== undefined) {
                result = result[k];
            } else {
                return undefined;
            }
        }
        if (typeof result === 'object' && result !== null) {
            const titleKey = `${key}_title`;
            if (translations[language] && typeof translations[language][titleKey] === 'string') {
                return translations[language][titleKey];
            }
            return undefined;
        }
        return result;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
